name: pRometheus

on:
  push:
  pull_request_target:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Print something
        run: composer lint

